### ISSUE TITLE
Make an endpoint to generate errors

### ISSUE THREAD

**Issue by sajal** [turbobytes/dummyorigin#8]
4xx and 5xx

    GET /err/503

Response should be status 503

**Comment by aaronpeters** [comment]
This would be useful:
/15kb.jpg?Cache-Control=30&stale-while-revalidate=900&stale-if-error=900

wait for 30 seconds

/switch/503
this instructs the server to send 503 response to whatever request

/15kb.jpg?Cache-Control=30&stale-while-revalidate=900&stale-if-error=900
does CDN now indeed serve stale?

/switch/normal
instruct server to behave as normal again

the /err/503 is nice but not useful for testing serve stale behavior because it cannot be used to serve an initial 200 response followed by an error response for that same file path
